### ISSUE TITLE
[all] Offline tests failing intermittently

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#1188]
This test sometimes fails in CI:
`sender + receiver install transfer successfully, receiver takes action, receiver uninstall protocol times out`

**Comment by rhlsthrm** [comment]
Saw a test failure here: `client proposes deposit, but node doesn't receive the NATS message (or no response from node)`

https://github.com/connext/indra/pull/1174/checks?check_run_id=726923117

Node logs snippet:

```
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:49.042Z [AppRegistryService] installOrReject for app 0xc66564f8b4d2883c9ebbf4c504b6eefd9527c30a98e2b50716e5c81ba62ada21 with params {"abiEncodings":{"actionEncoding":null,"stateEncoding":"tuple( tuple( address to, uint256 amount)[2] transfers, address multisigAddress, address assetId, uint256 startingTotalAmountWithdrawn, uint256 startingMultisigBalance,)"},"appDefinition":"0x345cA3e014Aaf5dcA488057592ee47305D9B3e10","initialState":{"transfers":[{"amount":{"_hex":"0x00"},"to":"0x9929eEcb0cfBaB033dA131812C0E5859eC267d7e"},{"amount":{"_hex":"0x00"},"to":"0x627306090abaB3A6e1400e9345bC60c78a8BEf57"}],"multisigAddress":"0x6678cE7fAfC370Bf3166F30aF77255Bf3d80dE8f","assetId":"0x0000000000000000000000000000000000000000","startingTotalAmountWithdrawn":{"_hex":"0x00"},"startingMultisigBalance":{"_hex":"0x0"}},"initiatorDeposit":{"_hex":"0x00"},"initiatorDepositAssetId":"0x0000000000000000000000000000000000000000","multisigAddress":"0x6678cE7fAfC370Bf3166F30aF77255Bf3d80dE8f","outcomeType":"SINGLE_ASSET_TWO_PARTY_COIN_TRANSFER","responderIdentifier":"indra8AXWmo3dFpK1drnjeWPyi9KTy9Fy3SkCydWx8waQrxhnW4KPmR","responderDeposit":{"_hex":"0x00"},"responderDepositAssetId":"0x0000000000000000000000000000000000000000","defaultTimeout":{"_hex":"0x21c0"},"stateTimeout":{"_hex":"0x21c0"},"initiatorIdentifier":"indra6tKKAooLttA72iABTmZttmRFZiE1T4MKPTny7AxsXgZQdH6jZj"} from indra6tKKAooLttA72iABTmZttmRFZiE1T4MKPTny7AxsXgZQdH6jZj started
163
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:49.042Z [CF-RequestHandler] Event for propose protocol was processed in 65 ms
164
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:49.046Z [CF-Install] Executing with params: {"appIdentityHash":"0xc665..da21","multisigAddress":"0x6678..dE8f"}
165
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:53.980Z [LockService] Releasing lock for 0x6678cE7fAfC370Bf3166F30aF77255Bf3d80dE8f after 5015 ms
166
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:53.983Z [LockService] Acquired lock for 0x6678cE7fAfC370Bf3166F30aF77255Bf3d80dE8f after waiting 4937 ms
167
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:53.991Z [CF-InstallProtocol] [50437165-07d7-43ca-983f-4b7a76f0a07a] Initiation started
168
indra_node.1.5dlna5qjhegd@fv-az128    | Signed 1101-byte bearer authorization token for subject: indra6tKKAooLttA72iABTmZttmRFZiE1T4MKPTny7AxsXgZQdH6jZj
169
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:54.166Z [LockService] Waiting on lock for 0x6678cE7fAfC370Bf3166F30aF77255Bf3d80dE8f (locked: 0x6678..dE8f)
170
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:59.002Z [CF-Install] Caught error in node controller: IO_SEND_AND_WAIT timed out after 5s waiting for counterparty reply in install
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:59.003Z [CF-Install] Released lock in 5012 ms
172
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:59.003Z [MessagingInterface] Responded to indra6tKKAooLttA72iABTmZttmRFZiE1T4MKPTny7AxsXgZQdH6jZj.lock.acquire.0x6678cE7fAfC370Bf3166F30aF77255Bf3d80dE8f in 4837 ms
173
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:59.004Z [AppRegistryService] App install failed: Error: IO_SEND_AND_WAIT timed out after 5s waiting for counterparty reply in install
174
indra_node.1.5dlna5qjhegd@fv-az128    |     at eval (webpack:///./node_modules/@connext/cf-core/dist/cfCore.js?:120:27)
175
indra_node.1.5dlna5qjhegd@fv-az128    |     at runNextTicks (internal/process/task_queues.js:58:5)
176
indra_node.1.5dlna5qjhegd@fv-az128    |     at processTimers (internal/timers.js:472:9)
177
indra_node.1.5dlna5qjhegd@fv-az128    |     at async ProtocolRunner.runProtocol (webpack:///./node_modules/@connext/cf-core/dist/machine/protocol-runner.js?:94:33)
178
indra_node.1.5dlna5qjhegd@fv-az128    |     at async ProtocolRunner.initiateProtocol (webpack:///./node_modules/@connext/cf-core/dist/machine/protocol-runner.js?:43:33)
179
indra_node.1.5dlna5qjhegd@fv-az128    |     at async install (webpack:///./node_modules/@connext/cf-core/dist/methods/app-instance/install.js?:49:46)
180
indra_node.1.5dlna5qjhegd@fv-az128    |     at async InstallAppInstanceController.executeMethodImplementation (webpack:///./node_modules/@connext/cf-core/dist/methods/app-instance/install.js?:35:37)
181
indra_node.1.5dlna5qjhegd@fv-az128    |     at async InstallAppInstanceController.executeMethod (webpack:///./node_modules/@connext/cf-core/dist/methods/controller.js?:37:22)
182
indra_node.1.5dlna5qjhegd@fv-az128    |     at async RpcRouter.dispatch (webpack:///./node_modules/@connext/cf-core/dist/rpc-router.js?:20:25)
183
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:59.004Z [LockService] Waiting on lock for 0x6678cE7fAfC370Bf3166F30aF77255Bf3d80dE8f (locked: 0x6678..dE8f)
184
indra_node.1.5dlna5qjhegd@fv-az128    | Signed 1101-byte bearer authorization token for subject: indra6tKKAooLttA72iABTmZttmRFZiE1T4MKPTny7AxsXgZQdH6jZj
185
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:54.117Z [CF-GetStateChannel] Executing with params: {"multisigAddress":"0x6678..dE8f"}
186
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:54.142Z [MessagingInterface] Responded to indra6tKKAooLttA72iABTmZttmRFZiE1T4MKPTny7AxsXgZQdH6jZj.channel.restore in 27 ms
187
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:59.002Z [LockService] Releasing lock for 0x6678cE7fAfC370Bf3166F30aF77255Bf3d80dE8f after 5019 ms
188
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:59.003Z [LockService] Acquired lock for 0x6678cE7fAfC370Bf3166F30aF77255Bf3d80dE8f after waiting 4837 ms
189
indra_node.1.5dlna5qjhegd@fv-az128    | 2020-06-01T10:09:59.004Z [CF-RejectInstall] Executing with params: {"appIdentityHash":"0xc665..da21","multisigAddress":"0x6678..dE8f"}
```
