### ISSUE TITLE
Bots throw errors while running concurrently

### ISSUE THREAD

**Issue by bohendo** [connext/indra#1227]
Bugs: When running the bots to play with max throughput yesterday, Arjun found two bugs that we need to fix asap:

1. Installation sometimes fails with an IO_SEND_AND_WAIT timeout on the receiver side.
2. `Validating signer` errors, usually in uninstall

Both of the above can be reproduced by spinning up many bots concurrently:
`bash ops/test/bot.sh 10 2000`

**Comment by bohendo** [comment]
Another error I've encountered:
```
2020-06-10T11:07:49.570Z E [Bot #2][CF-ProposeInstall] Caught error in node controller: Error: Error: Cannot install two deposit apps with the same asset id simultaneously. Existing app: 0x398384dda6ed1e92174600051635363eb4781e0e1f5f11345d949f9762a59c33
    at proposeDepositMiddleware (/root/modules/apps/dist/index.js:151:15)
    at proposeMiddleware (/root/modules/apps/dist/index.js:417:19)
    at validationMiddleware (/root/modules/apps/dist/index.js:379:23)
    at /root/modules/cf-core/dist/cfCore.js:82:27
    at MiddlewareContainer.run (/root/modules/cf-core/dist/machine/middleware.js:27:16)
    at ProtocolRunner.runProtocol (/root/modules/cf-core/dist/machine/protocol-runner.js:94:56)
    at async ProtocolRunner.initiateProtocol (/root/modules/cf-core/dist/machine/protocol-runner.js:43:33)
    at async ProposeInstallAppInstanceController.executeMethodImplementation (/root/modules/cf-core/dist/methods/app-instance/propose-install.js:37:38)
    at async ProposeInstallAppInstanceController.executeMethod (/root/modules/cf-core/dist/methods/controller.js:37:22)
    at async RpcRouter.dispatch (/root/modules/cf-core/dist/rpc-router.js:20:25)
    at /root/modules/cf-core/dist/protocol/propose.js:54:23
    at Generator.next (<anonymous>)
    at resume (/root/modules/cf-core/dist/protocol/propose.js:8:44)
    at /root/modules/cf-core/dist/protocol/propose.js:7:121
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/root/modules/cf-core/dist/protocol/propose.js:7:63)
    at ProtocolRunner.runProtocol (/root/modules/cf-core/dist/machine/protocol-runner.js:89:39)
    at async ProtocolRunner.initiateProtocol (/root/modules/cf-core/dist/machine/protocol-runner.js:43:33)
    at async ProposeInstallAppInstanceController.executeMethodImplementation (/root/modules/cf-core/dist/methods/app-instance/propose-install.js:37:38)
    at async ProposeInstallAppInstanceController.executeMethod (/root/modules/cf-core/dist/methods/controller.js:37:22)
    at async RpcRouter.dispatch (/root/modules/cf-core/dist/rpc-router.js:20:25)
```
while bots are trying to deposit.

**Comment by bohendo** [comment]
And another:
```
2020-06-10T11:23:31.251Z E [Bot #6][CF-Uninstall] Caught error in node controller: Error: No appInstance exists for identity hash 0x463a4299b1797ad485f5172b8630f1780aaa5841bc9ea0a84bf25e113e497ce6
    at UninstallController.beforeExecution (/root/modules/cf-core/dist/methods/app-instance/uninstall.js:34:19)
    at UninstallController.executeMethod (/root/modules/cf-core/dist/methods/controller.js:34:24)
    at async RpcRouter.dispatch (/root/modules/cf-core/dist/rpc-router.js:20:25)
UnhandledPromiseRejection detected. Crashing..
```
This appeared to have been encountered while uninstalling the deposit app

**Comment by rhlsthrm** [comment]
Closing this issue. The validating sig errors are due to bots timing out during protocols and getting out of sync.
