### ISSUE TITLE
Depositing fails if INDRA_SUPPORTED_TOKENS isn't defined

### ISSUE THREAD

**Issue by Jannis** [connext/indra#1236]
**Describe the bug**

When running the node without the `INDRA_SUPPORTED_TOKENS` environment variable set, depositing with
```js
await channel.deposit({ amount: ... })
```
fails with the following error in the node logs:
```
020-06-14T20:00:35.061Z [CF-handleReceivedProtocolMessage] Caught error running propose protocol, aborting. Error: Error: Error: Unsupported initiatorDepositTokenAddress: 0x0000000000000000000000000000000000000000, supported addresses: []
    at commonAppProposalValidation (webpack:///./node_modules/@connext/apps/dist/index.esm.js?:92:15)
    at sharedProposalMiddleware (webpack:///./node_modules/@connext/apps/dist/index.esm.js?:409:12)
    at proposeMiddleware (webpack:///./node_modules/@connext/apps/dist/index.esm.js?:452:5)
    at validationMiddleware (webpack:///./node_modules/@connext/apps/dist/index.esm.js?:418:23)
    at AppRegistryService.eval (webpack:///./src/appRegistry/appRegistry.service.ts?:62:27)
    at Generator.next (<anonymous>)
    at eval (webpack:///./src/appRegistry/appRegistry.service.ts?:17:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack:///./src/appRegistry/appRegistry.service.ts?:13:12)
    at eval (webpack:///./src/appRegistry/appRegistry.service.ts?:61:43)
    at eval (webpack:///./node_modules/@connext/cf-core/dist/cfCore.js?:82:27)
    at MiddlewareContainer.run (webpack:///./node_modules/@connext/cf-core/dist/machine/middleware.js?:27:16)
    at ProtocolRunner.runProtocol (webpack:///./node_modules/@connext/cf-core/dist/machine/protocol-runner.js?:94:56)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ProtocolRunner.runProtocolWithMessage (webpack:///./node_modules/@connext/cf-core/dist/machine/protocol-runner.js?:31:33)
    at eval (webpack:///./node_modules/@connext/cf-core/dist/protocol/propose.js?:136:23)
    at Generator.next (<anonymous>)
    at resume (webpack:///./node_modules/@connext/cf-core/dist/protocol/propose.js?:8:44)
    at eval (webpack:///./node_modules/@connext/cf-core/dist/protocol/propose.js?:7:121)
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (webpack:///./node_modules/@connext/cf-core/dist/protocol/propose.js?:7:63)
    at ProtocolRunner.runProtocol (webpack:///./node_modules/@connext/cf-core/dist/machine/protocol-runner.js?:89:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ProtocolRunner.runProtocolWithMessage (webpack:///./node_modules/@connext/cf-core/dist/machine/protocol-runner.js?:31:33)
    at async handleReceivedProtocolMessage (webpack:///./node_modules/@connext/cf-core/dist/message-handling/handle-protocol-message.js?:19:41)
    at async RequestHandler.callEvent (webpack:///./node_modules/@connext/cf-core/dist/request-handler.js?:65:13)
    at async CFCore.handleReceivedMessage (webpack:///./node_modules/@connext/cf-core/dist/cfCore.js?:252:17)
    at async eval (webpack:///./node_modules/@connext/cf-core/dist/cfCore.js?:234:21)
```

**Expected behavior**

The expected behavior is that depositing works using `0x0000000000000000000000000000000000000000`, even if the environment variable is not defined.

**Your Environment**

* Client version used: 7.0.0-alpha.0
* Node version used: v12.16.3
* Chain used: Kovan
* Browser Name and version: -
* Operating System and version (desktop or mobile): macOS 10.15.5

**Comment by Jannis** [comment]
I can confirm that setting the environment variable to
```yaml
- name: INDRA_SUPPORTED_TOKENS
   value: 0x090579CeDaDE1DCdB11b3deDC2B271aA472C4007,0x0000000000000000000000000000000000000000
```
for Kovan works.

**Comment by ArjunBhuptani** [comment]
Copying my post in discord here for reference:

> One thing to be careful of here -- while I think it makes sense to have sane defaults, if the node operator leaves AddressZero allowed when they dont support it, that's going to lead to bugs for sure. E.g. user attempts to transfer using Eth (not knowing that the node is set up to use Dai), and ends up locking up all of the node's gas money

**Comment by ArjunBhuptani** [comment]
Update - it's good enough here to just have a clearly worded error message so that the user can fix this themselves

**Comment by bohendo** [comment]
Closing this issue in favor of #922. The supported tokens env var will be going away entirely as part of resolving issue #922 bc we're reorganizing env vars & will derive supported tokens from the provided/supported chainIds & the address book.
