### ISSUE TITLE
Investigate and reproduce lock failure issues

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#1335]
![a](https://user-images.githubusercontent.com/22877754/88453188-d21f8d00-ce75-11ea-9288-2db856f12aad.png)

Started with 
```
{
  "textPayload": "\u001b[0m2020-07-24T19:05:01.687Z \u001b[36m[MessagingInterface]\u001b[0m \u001b[31mError: Queue is full.\n    at eval (webpack:///./src/lock/memo-lock.ts?:156:39)\n    at tryCatcher (/root/node_modules/standard-as-callback/built/utils.js:11:23)\n    at /root/node_modules/standard-as-callback/built/index.js:19:49\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\u001b[0m\n"
}
```

Then 
```
{
  "textPayload": "\u001b[0m2020-07-24T19:05:03.580Z \u001b[36m[LockService]\u001b[0m \u001b[31mError unlocking resource 0x573FF1012401Eda7ddb0dEbA7FA5372e45d84C16 (f4a78e084cc93133ec6aef0fbf2adec4): Error: Trying to unlock invalid lock: 0x573FF1012401Eda7ddb0dEbA7FA5372e45d84C16 f4a78e084cc93133ec6aef0fbf2adec4\n    at eval (webpack:///./src/lock/memo-lock.ts?:171:39)\n    at tryCatcher (/root/node_modules/standard-as-callback/built/utils.js:11:23)\n    at /root/node_modules/standard-as-callback/built/index.js:19:49\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\u001b[0m\n"
}
```

```
{
  "textPayload": "\u001b[0m2020-07-24T19:05:04.401Z \u001b[36m[LockService]\u001b[0m \u001b[31mFailed to lock resource 0x573FF1012401Eda7ddb0dEbA7FA5372e45d84C16: Lock 0x573FF1012401Eda7ddb0dEbA7FA5372e45d84C160ad941b9629a8c8ed188be5564dfccda expired after 21000 seconds.\u001b[0m\n"
}
```

Possibly related:
```
{
  "textPayload": "\u001b[0m2020-07-24T19:05:20.233Z \u001b[36m[LockService]\u001b[0m \u001b[33mWaiting on lock for 0x573FF1012401Eda7ddb0dEbA7FA5372e45d84C16 (locked: 0x2751..681c,0xd981..471e,0xf715..c6db,0x2bbb..5cd9,0xd1f8..ed5a,0xbafe..c075,0xfbef..e942,0x360d..7dd5,0x573F..4C16)\u001b[0m\n"
}
```

Then finally breaks with:
```
{
  "textPayload": "\u001b[0m2020-07-24T19:05:25.387Z \u001b[36m[CF-handleReceivedProtocolMessage]\u001b[0m \u001b[33mCaught error running propose protocol, aborting. Will be retried after syncing. Error: Validating a signature with expected signer 0x19b42F30881e7317359fB5500041091635A4F3E0 but recovered 0x854Ad18467994d8448926aEa8ffD011C328cA483 for commitment hash 0xf2b417488ac9e350bff3619cbb804373e45e652e4498af9a04659b285ba19de5. Failed to validate initiator's signature on initial set state commitment in the propose protocol. Process: a1283f23-8c0c-428d-b419-13272af6d31e. Our commitment: {\n"
}```

**Comment by ArjunBhuptani** [comment]
![unknown](https://user-images.githubusercontent.com/22877754/88482586-57d53280-cf73-11ea-896f-0425108d0cfa.png)
![unknown1](https://user-images.githubusercontent.com/22877754/88482589-59065f80-cf73-11ea-918d-b12880fcc786.png)

**Comment by ArjunBhuptani** [comment]
Closing for now until we find more info
